{ pkgs, ... }:
{
  # niri config (~/.config/niri/config.kdl) is generated by `dms setup`, not managed here.
  home.username = "on3i";
  home.homeDirectory = "/home/on3i";
  home.stateVersion = "26.05";

  home.packages = with pkgs; [ wl-clipboard cliphist ];
}
