{ pkgs, modulesPath, ... }:
# Regenerated by `nixos-generate-config` on the installer; re-apply stump tweaks after.
{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.kernelPackages = pkgs.linuxPackages;
  boot.blacklistedKernelModules = [ "nouveau" ];

  hardware.cpu.intel.updateMicrocode = true; # info:hardware.cpu.intel.updateMicrocode 26.05
  hardware.enableRedistributableFirmware = true; # info:hardware.enableRedistributableFirmware 26.05
  hardware.graphics = {
    enable = true; # info:hardware.graphics.enable 26.05
    enable32Bit = true; # info:hardware.graphics.enable32Bit 26.05
  };

  services.xserver.videoDrivers = [ "modesetting" ];

  nixpkgs.hostPlatform = "x86_64-linux";
}
